Enabling pylint's `unused-argument` flag
Infleqtion/client-superstaq pull request #982
Opened 2024-07-05 19:31 UTC by spencerdearman

- Updates to include the `unused-argument` flag in the pyproject.toml file
- Updates various files that were flagged when running `./pylint_.py --all`

Closes #981

2024-07-05 19:31 UTC, spencerdearman commented
https://github.com/Infleqtion/server-superstaq/pull/3273

2024-07-05 19:31 UTC, spencerdearman commented
#https://github.com/Infleqtion/server-superstaq/pull/3273

2024-07-05 21:24 UTC, vtomole requested changes
Looks good so far. Now, fix all the `unused arguments` errors and remove the `# pylint: disable=unused-argument`s

2024-07-05 21:29 UTC, richrines1 reviewed
(a few notes)

2024-07-05 21:29 UTC, richrines1 commented on qiskit-superstaq/qiskit_superstaq/custom_gates.py
>          return np.array([[0, -1j], [-1j, 0]])
```suggestion
        return np.array([[0, -1j], [-1j, 0]], dtype=dtype)
```

2024-07-05 21:29 UTC, richrines1 commented on qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
> +        # pylint: disable=unused-argument
which argument isn't used here?

2024-07-05 21:29 UTC, richrines1 commented on qiskit-superstaq/qiskit_superstaq/custom_gates.py
>          return qiskit.quantum_info.Operator(self.definition).data
ideally we should be doing something with the correct precision here, but for now we can use something like
```suggestion
        matrix = qiskit.quantum_info.Operator(self.definition).to_matrix()
        return np.asarray(matrix, dtype=dtype)
```

2024-07-08 16:33 UTC, spencerdearman commented
I went through and resolved what @richrines1 suggested. Let me know if there is anything I missed/if you have any other changes that I should make.

2024-07-18 16:45 UTC, richrines1 reviewed
looks good, just some nits

2024-07-18 16:45 UTC, richrines1 commented on cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
> +    def _from_json_dict_(cls, component_gates: list[cirq.Gate], **_kwargs: Any) -> ParallelGates:
predates this pr, but while we're here i think this should just be
```suggestion
    def _from_json_dict_(cls, component_gates: list[cirq.Gate], **_kwargs: object) -> ParallelGates:
```

2024-07-18 16:45 UTC, richrines1 commented on cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
>          return IXGate()
```suggestion
    def _from_json_dict_(cls, **_kwargs: object) -> IXGate:
        return cls()
```

2024-07-18 19:04 UTC, richrines1 approved these changes
lgtm!

2024-07-18 21:44 UTC, spencerdearman reviewed
Fixed issues

2024-07-22 15:05 UTC, vtomole approved these changes
LGTM

2024-07-22 15:18 UTC, merged